### ISSUE TITLE
thanks and tokio

### ISSUE THREAD

**Issue by gs-sa** [marcbone/libfranka-rs#3]
this crate works really good on my robot, thank you

I noticed that you using mio to control tcp udp sockets, but mio is low level. do you have any plan or consideration to use tokio?

**Comment by marcbone** [comment]
Thank you very much. From all of my repos, this is the one I am most proud of as it is to my knowledge the first rust crate that can do real-time control of a real robot.
I thought about supporting async, however the main "mission" I want to achieve with this library is for robotics to try out rust. Therefore, I would like to keep it as simple as possible and not force them to also learn async. I would love to have an "async" feature that could be activated that makes every method async, but I have quite some doubts whether this would be very maintainable. Also I currently focusing on supporting [both robots at the same time](https://github.com/marcbone/libfranka-rs/pull/2). So if you have an idea how async could be achieved without basically maintaining two versions of the library please let me know.

**Comment by gs-sa** [comment]
thank your reply

this is also the first rust code I wrote that makes a real thing move, I used to use ros to control franka, but ros made me nearly crazy, thank your crate that make things really easy.

I understand your worry and thinking about the target and maintainable. It's good to keep code simple since there no solid requirement on async feature. currently you need to write async trait to painless integrate with the sync trait, and implement both async and sync version for one function.

I'm not a very skilled rustacean, so sorry I can't help you to pr async feature since async is pretty uneasy.

btw: I saw you mentioned this crate could work on macOS, and I tested, it didn't 😢. Because model can't load on macos(model.so is not a [Mach Object](https://www.lifewire.com/dylib-file-2620908)), if you work in franka, meybe you can make some change.
